---
# configs
- hosts: localhost
  tasks:
    - name: install dotfiles
      file:
        src: "{{ playbook_dir }}/dotfiles/{{ item }}"
        dest: "~/{{ item }}"
        state: link
      with_items: "{{ dotfiles }}"
