---
- hosts: localhost
  tasks:
    - name: git clone doom-emacs
      git:
        repo: https://github.com/hlissner/doom-emacs
        dest: ~/github/doom-emacs
        update: no

    - name: install .emacs.d
      file:
        src: ~/github/doom-emacs
        dest: ~/.emacs.d
        state: link

    - name: install .doom.d
      file:
        src: ~/github/.doom.d
        dest: ~/.doom.d
        state: link

    - name: install snap packages
      become: true
      snap:
        name: ccls
        classic: true
