---
- hosts: localhost
  tasks:
    - name: git clone doom-emacs
      git:
        repo: https://github.com/hlissner/doom-emacs
        dest: ~/.emacs.d

    - name: install .doom.d
      file:
        src: ~/github/.doom.d
        dest: ~/.doom.d
        state: link
