---
- hosts: localhost
  tasks:
    - name: install .emacs.d
      file:
        src: ~/github/.emacs.d
        dest: ~/.emacs.d
        state: link

    - name: install snap packages
      become: true
      snap:
        name: ccls
        classic: true

    - name: download dash docsets
      get_url:
        url: "http://london.kapeli.com/feeds/{{ item }}.tgz"
        dest: "~/docsets/{{ item }}.tgz"
      with_items: "{{ dash_docsets }}"

    - name: install .doom.d
      file:
        src: ~/github/doom-emacs
        dest: ~/.doom.d
        state: link
