---
- hosts: localhost
  tasks:
    - name: install .emacs.d
      file:
        src: ~/github/.emacs.d
        dest: ~/.emacs.d
        state: link

    - name: install snap packages
      become: true
      snap:
        name: ccls
        classic: true
