---
- hosts: localhost
  tasks:
    - name: git clone gdb-dashboard
      git:
        repo: https://github.com/cyrus-and/gdb-dashboard.git
        dest: ~/src/gdb-dashboard
        update: no

    - name: install gdbinit
      file:
        src: ~/src/gdb-dashboard/.gdbinit
        dest: ~/.gdbinit
        state: link
