---
- hosts: localhost
  tasks:
    - name: install common deb packages
      become: true
      apt:
        name: "{{ common_deb_packages }}"

    - name: install dev deb packages
      become: true
      apt:
        name: "{{ development_deb_packages }}"

    - name: install python-pip
      become: true
      apt:
        name: python3-pip

    - name: install common pip packages
      pip:
        name: "{{ common_pip_packages }}"
        extra_args: --user

    - name: install dev pip packages
      pip:
        name: "{{ development_pip_packages }}"
        extra_args: --user

    # - name: install snap packages
    #   become: true
    #   snap:
    #     name: "{{ snap_packages }}"
    #     classic: true
